-- V1 : schéma initial, conforme au diagramme D2 (docs/diagrammes/D2-modele-donnees.md).
-- SQL portable PostgreSQL 16 / H2 (MODE=PostgreSQL). Dates en UTC.

CREATE TABLE promotion (
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    CONSTRAINT uk_promotion_nom UNIQUE (nom)
);

CREATE TABLE etudiant (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom            VARCHAR(100) NOT NULL,
    promotion_id   BIGINT       NOT NULL,
    erreurs_code   INTEGER      NOT NULL DEFAULT 0,        -- RG4 (étape 4)
    bloque_jusqu_a TIMESTAMP WITH TIME ZONE,               -- RG4 (étape 4)
    CONSTRAINT fk_etudiant_promotion FOREIGN KEY (promotion_id) REFERENCES promotion (id)
);
CREATE INDEX idx_etudiant_promotion ON etudiant (promotion_id);

CREATE TABLE session (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre         VARCHAR(200)             NOT NULL,
    promotion_id  BIGINT                   NOT NULL,
    code          VARCHAR(6)               NOT NULL,       -- unique parmi les sessions non expirées (H5)
    ouverture_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    expiration_at TIMESTAMP WITH TIME ZONE NOT NULL,       -- ouverture + 15 min (RG1)
    cloture_at    TIMESTAMP WITH TIME ZONE,                -- NULL tant que non clôturée (H2)
    CONSTRAINT fk_session_promotion FOREIGN KEY (promotion_id) REFERENCES promotion (id)
);
CREATE INDEX idx_session_code ON session (code);
CREATE INDEX idx_session_promotion ON session (promotion_id);

CREATE TABLE presence (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  BIGINT                   NOT NULL,
    etudiant_id BIGINT                   NOT NULL,
    source      VARCHAR(20)              NOT NULL,
    marquee_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_presence_session FOREIGN KEY (session_id) REFERENCES session (id),
    CONSTRAINT fk_presence_etudiant FOREIGN KEY (etudiant_id) REFERENCES etudiant (id),
    CONSTRAINT uk_presence_session_etudiant UNIQUE (session_id, etudiant_id),              -- RG2
    CONSTRAINT ck_presence_source CHECK (source IN ('ETUDIANT', 'FORMATEUR'))            -- RG5
);
CREATE INDEX idx_presence_etudiant ON presence (etudiant_id);

CREATE TABLE exercice (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  BIGINT                   NOT NULL,
    etudiant_id BIGINT                   NOT NULL,         -- auteur
    lien        VARCHAR(2000)            NOT NULL,         -- URL http(s) (RG16)
    statut      VARCHAR(30)              NOT NULL,
    depose_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_exercice_session FOREIGN KEY (session_id) REFERENCES session (id),
    CONSTRAINT fk_exercice_etudiant FOREIGN KEY (etudiant_id) REFERENCES etudiant (id),
    CONSTRAINT uk_exercice_session_etudiant UNIQUE (session_id, etudiant_id),              -- RG6
    CONSTRAINT ck_exercice_statut CHECK (statut IN ('DEPOSE', 'EN_ATTENTE_RELECTURE', 'RELU')) -- D4
);
CREATE INDEX idx_exercice_etudiant ON exercice (etudiant_id);

CREATE TABLE relecture (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercice_id  BIGINT                   NOT NULL,
    relecteur_id BIGINT                   NOT NULL,        -- jamais l'auteur (RG10, contrôlé par le service)
    note         INTEGER,
    commentaire  VARCHAR(2000),
    assignee_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    rendue_at    TIMESTAMP WITH TIME ZONE,                 -- NULL tant que non rendue (RG12, RG14)
    CONSTRAINT fk_relecture_exercice FOREIGN KEY (exercice_id) REFERENCES exercice (id),
    CONSTRAINT fk_relecture_relecteur FOREIGN KEY (relecteur_id) REFERENCES etudiant (id),
    CONSTRAINT uk_relecture_exercice UNIQUE (exercice_id),                                 -- RG9
    CONSTRAINT ck_relecture_note CHECK (note BETWEEN 0 AND 20)                            -- RG11
);
CREATE INDEX idx_relecture_relecteur ON relecture (relecteur_id);
